# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "hits", :force => true do |t|
    t.column "title",                       :string,                :default => "",    :null => false
    t.column "description",                 :text,                  :default => "",    :null => false
    t.column "blogURL",                     :string,                :default => "",    :null => false
    t.column "rewardAmount",                :float,                 :default => 0.0,   :null => false
    t.column "rewardCurrency",              :string,  :limit => 3,  :default => "",    :null => false
    t.column "assignmentDurationInSeconds", :integer,               :default => 0,     :null => false
    t.column "lifetimeInSeconds",           :integer,               :default => 0,     :null => false
    t.column "keywords",                    :text
    t.column "maxAssignments",              :integer
    t.column "autoApprovalDelayInSeconds",  :integer
    t.column "qualificationRequirements",   :text
    t.column "hitId",                       :string,  :limit => 20, :default => "",    :null => false
    t.column "typeId",                      :string,  :limit => 20, :default => "",    :null => false
    t.column "sandbox",                     :boolean,               :default => false, :null => false
  end

  create_table "qualification_requests", :force => true do |t|
    t.column "request_id",  :text,     :default => "", :null => false
    t.column "type_id",     :string,   :default => "", :null => false
    t.column "subject_id",  :string,   :default => "", :null => false
    t.column "test",        :text,     :default => "", :null => false
    t.column "answer",      :text,     :default => "", :null => false
    t.column "submit_time", :datetime,                 :null => false
    t.column "approved",    :boolean
  end

  create_table "qualifications", :force => true do |t|
    t.column "name",                  :string,   :default => "",    :null => false
    t.column "description",           :text,     :default => "",    :null => false
    t.column "keywords",              :text
    t.column "retryDelayInSeconds",   :integer
    t.column "qualificationIsActive", :boolean,  :default => false, :null => false
    t.column "testXML",               :text
    t.column "answerKeyXML",          :text
    t.column "testDurationInSeconds", :integer
    t.column "autoGranted",           :boolean,  :default => false, :null => false
    t.column "autoGrantedValue",      :integer
    t.column "isSystemQualification", :boolean,  :default => false, :null => false
    t.column "isLocaleValue",         :boolean,  :default => false, :null => false
    t.column "qualificationTypeId",   :string
    t.column "creationTime",          :datetime
  end

  create_table "system_settings", :force => true do |t|
    t.column "name",  :string, :default => "", :null => false
    t.column "value", :text,   :default => "", :null => false
  end

  add_index "system_settings", ["name"], :name => "index_system_settings_on_name", :unique => true

end
